apiVersion: apps/v1
kind: Deployment
metadata:
  name: yahoo-download-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yahoo-download
  template:
    metadata:
      labels:
        app: yahoo-download
    spec:
      containers:
        - name: yahoo-download-container
          image: ccr.ccs.tencentyun.com/1223/yahoo-download:latest
          # 确保每次启动都拉取最新镜像，防止代码更新了但容器没变
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
